/* ==========================================================================
   DHCODE — Product Database
   Mỗi sản phẩm có: id, title, category, icon (Font Awesome, dùng để vẽ
   preview khi chưa có ảnh thật), gradient (màu preview card), description,
   price, author, demo, download, rating.
   ========================================================================== */

const CATEGORIES = [
  { key: "all",        label: "Tất cả",            icon: "fa-layer-group" },
  { key: "website",    label: "Website Template",   icon: "fa-desktop" },
  { key: "landing",    label: "Landing Page",       icon: "fa-globe" },
  { key: "game",       label: "Game Source",        icon: "fa-gamepad" },
  { key: "tool",       label: "Developer Tool",     icon: "fa-screwdriver-wrench" },
  { key: "ai",         label: "AI Project",         icon: "fa-robot" },
  { key: "app",        label: "App Source",         icon: "fa-mobile-screen-button" },
  { key: "ui",         label: "UI Template",        icon: "fa-palette" },
];

const PRODUCTS = [
  {
    id: 1,
    title: "Developer Portfolio",
    category: "website",
    icon: "fa-id-badge",
    gradient: "grad-1",
    image: "assets/images/demo.png",
    description: "Modern portfolio website for developers, kèm dark mode và hiệu ứng scroll mượt.",
    price: "99.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 2,
    title: "Mẫu tặng valentine",
    category: "Website",
    icon: "fa-code",
    gradient: "grad-2",
    image: "assets/images/demo.png",
    description: "Web siêu xịn, đẹp, phù hợp với các dịp valentine, 20/10,....",
    price: "100.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 3,
    title: "Pixel Runner Game",
    category: "game",
    icon: "fa-person-running",
    gradient: "grad-3",
    image: "assets/images/demo.png",
    description: "Mini game endless-runner viết bằng JS thuần, dễ tích hợp vào web.",
    price: "79.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 4,
    title: "JSON Formatter Pro",
    category: "tool",
    icon: "fa-code",
    gradient: "grad-4",
    image: "assets/images/demo.png",
    description: "Công cụ format & validate JSON online, chạy 100% phía client.",
    price: "49.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 5,
    title: "AI Chatbot Widget",
    category: "ai",
    icon: "fa-comment-dots",
    gradient: "grad-5",
    image: "assets/images/demo.png",
    description: "Widget chatbot AI nhúng vào bất kỳ website nào chỉ với 1 dòng script.",
    price: "199.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 6,
    title: "Fitness Tracker App UI",
    category: "app",
    icon: "fa-heart-pulse",
    gradient: "grad-6",
    image: "assets/images/demo.png",
    description: "Source code app theo dõi sức khỏe, UI hiện đại, chart trực quan.",
    price: "129.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 7,
    title: "Glass Dashboard UI",
    category: "ui",
    icon: "fa-chart-pie",
    gradient: "grad-1",
    image: "assets/images/demo.png",
    description: "Bộ UI kit dashboard phong cách glassmorphism, đầy đủ component.",
    price: "159.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 8,
    title: "Agency Website Template",
    category: "website",
    icon: "fa-building",
    gradient: "grad-2",
    image: "assets/images/demo.png",
    description: "Website giới thiệu agency/công ty, tối ưu SEO và tốc độ tải trang.",
    price: "119.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 9,
    title: "App Launch Landing",
    category: "landing",
    icon: "fa-mobile",
    gradient: "grad-3",
    image: "assets/images/demo.png",
    description: "Landing page ra mắt ứng dụng di động, có mockup 3D & CTA nổi bật.",
    price: "99.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 10,
    title: "2D Platformer Engine",
    category: "game",
    icon: "fa-chess-board",
    gradient: "grad-4",
    image: "assets/images/demo.png",
    description: "Engine nền tảng cho game platformer 2D, physics & collision sẵn có.",
    price: "249.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 11,
    title: "Regex Tester Tool",
    category: "tool",
    icon: "fa-magnifying-glass",
    gradient: "grad-5",
    image: "assets/images/demo.png",
    description: "Công cụ kiểm tra biểu thức chính quy realtime, highlight kết quả khớp.",
    price: "39.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 12,
    title: "AI Image Caption Generator",
    category: "ai",
    icon: "fa-image",
    gradient: "grad-6",
    image: "assets/images/demo.png",
    description: "Dự án AI sinh caption cho ảnh, tích hợp sẵn API và UI demo.",
    price: "229.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 13,
    title: "Food Delivery App Source",
    category: "app",
    icon: "fa-utensils",
    gradient: "grad-1",
    image: "assets/images/demo.png",
    description: "Source code app đặt đồ ăn, đầy đủ luồng đặt hàng & thanh toán demo.",
    price: "279.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 14,
    title: "Neon UI Component Kit",
    category: "ui",
    icon: "fa-bolt",
    gradient: "grad-2",
    image: "assets/images/demo.png",
    description: "Bộ component UI phong cách neon-tech, sẵn sàng cho dashboard & app.",
    price: "139.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 15,
    title: "Developer CV Template",
    category: "website",
    icon: "fa-file-lines",
    gradient: "grad-3",
    image: "assets/images/demo.png",
    description: "Mẫu CV online cho lập trình viên, xuất PDF & responsive hoàn toàn.",
    price: "69.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 16,
    title: "Crypto Landing Page",
    category: "landing",
    icon: "fa-coins",
    gradient: "grad-4",
    image: "assets/images/demo.png",
    description: "Landing page dự án crypto/token, có countdown & roadmap timeline.",
    price: "109.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 17,
    title: "Memory Match Game",
    category: "game",
    icon: "fa-clone",
    gradient: "grad-5",
    image: "assets/images/demo.png",
    description: "Mini game lật hình ghi nhớ, code JS thuần, dễ tuỳ biến hình ảnh.",
    price: "59.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
  {
    id: 18,
    title: "Color Palette Generator",
    category: "tool",
    icon: "fa-swatchbook",
    gradient: "grad-6",
    image: "assets/images/demo.png",
    description: "Công cụ sinh bảng màu ngẫu nhiên hoặc theo màu gốc, xuất mã HEX/RGB.",
    price: "45.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 19,
    title: "AI Resume Analyzer",
    category: "ai",
    icon: "fa-file-circle-check",
    gradient: "grad-1",
    image: "assets/images/demo.png",
    description: "Dự án AI phân tích CV và gợi ý cải thiện nội dung, kèm UI demo.",
    price: "219.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 5,
  },
  {
    id: 20,
    title: "Portfolio Grid UI",
    category: "ui",
    icon: "fa-table-cells",
    gradient: "grad-2",
    image: "assets/images/demo.png",
    description: "Bộ UI dạng lưới cho portfolio/case study, animation hover tinh tế.",
    price: "89.000 VNĐ",
    author: "Doan Hoang",
    demo: "#",
    download: "#",
    rating: 4,
  },
];

/* Sản phẩm nổi bật cho carousel Trending */
const TRENDING_IDS = [5, 10, 2, 13, 19];
